name: Build, Scan, Deploy to k3d & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: fastapi-app
  IMAGE_TAG: latest
  REGISTRY_IMAGE: fastapi-app:latest
  CLUSTER_NAME: fastapi-app

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Build Docker Image
      - name: Build Docker Image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Tag & Push Image to DockerHub
      - name: Tag & Push Image
        run: |
          docker tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      # Install k3d
      - name: Install k3d
        run: |
          curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash

      # Create k3d Cluster with port mapping
      - name: Create k3d Cluster
        run: |
          k3d cluster create ${{ env.CLUSTER_NAME }} --agents 0 -p "8000:30007@server:0" || echo "Cluster exists"

      # Load DockerHub image into k3d (pulls from registry)
      - name: Pull image inside k3d nodes
        run: |
          k3d image import ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
            -c ${{ env.CLUSTER_NAME }}

      # Deploy Kubernetes manifests
      - name: Deploy manifests
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

      # Wait for deployment to be ready
      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/gpt-huggingface --timeout=180s

      - name: Print pod logs
        run: |
          kubectl get pods
          POD=$(kubectl get pods -o name | head -n 1)
          kubectl logs $POD --tail=50

      - name: Debug service endpoints
        run: |
            kubectl get svc
            kubectl get svc gpt-hf-service -o wide
            kubectl get endpoints gpt-hf-service -o wide
            kubectl get pods --show-labels
            kubectl get endpoints gpt-hf-service -o wide