name: Trivy Scan & DockerHub Push
 
on:

  push:

    branches: [ "main" ]

  pull_request:

    branches: [ "main" ]
 
jobs:

  build-scan-push:

    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          docker build -t ${{ github.repository }}:latest .
      - name: Run Trivy Scan on Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ github.repository }}:latest'
          format: 'table'
          exit-code: '1'       # FAIL pipeline if vulnerabilities found
          ignore-unfixed: true # optional
          vuln-type: 'os,library'

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Tag & Push Image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/llmops-e2e:latest
          docker tag ${{ github.repository }}:latest $IMAGE_NAME
          docker push $IMAGE_NAME
